services:
  - type: web
    name: recipes-app
    runtime: node
    plan: free
    buildCommand: npm run render:build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
